name: kawaii_mobile_app
description: "KawaiiChain 数字钱包移动端应用，支持提币、转账、生活缴费。"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: ">=3.18.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^16.2.1

  # State Management
  provider: ^6.1.2

  # Network
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0

  # Storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

  # Forms & Validation
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.0.0

  # Security & Biometrics
  local_auth: ^2.3.0
  crypto: ^3.0.6
  encrypt: ^5.0.3

  # Device Info
  device_info_plus: ^12.1.0
  package_info_plus: ^9.0.0

  # Utils
  intl: ^0.20.2
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.13
  retrofit_generator: ^10.0.5
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

  # Fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
